#ifndef KV_HW_DRIVER_H
#define KV_HW_DRIVER_H

/* =============================================================================
 * KV Cache Hardware Driver
 * Target  : Arty Z7 (Zynq-7020)
 * AXI4-Lite Slave @ KV_BASE_ADDR (from xparameters.h)
 *
 * Architecture:
 *   PS → AXI Interconnect → AXI4-Lite Wrapper → Core Cache FSM
 *   Core: 512 Set × 8 Way BRAM, Delta Codec, Immune/Locked Zone logic
 *   Eviction: PLRU / FIFO / Random (selectable at runtime)
 *   Overflow: AXI4-Full → DDR via S_AXI_HP0 @ 0x11000000
 * ============================================================================= */

#include "xil_io.h"
#include "xparameters.h"
#include "sleep.h"

/* ---------------------------------------------------------------------------
 * Base address — from xparameters.h generated by Vivado/Vitis
 * --------------------------------------------------------------------------- */
#ifndef KV_BASE_ADDR
#define KV_BASE_ADDR    XPAR_KV_CACHE_AXI_WRAPPER_0_BASEADDR
#endif

/* ---------------------------------------------------------------------------
 * Register offsets
 * --------------------------------------------------------------------------- */
#define KV_REG0_CTRL    (KV_BASE_ADDR + 0x00U)   /* Control & Status          */
#define KV_REG1_COORD   (KV_BASE_ADDR + 0x04U)   /* Layer[31:16] | Head[15:0] */
#define KV_REG2_TOKEN   (KV_BASE_ADDR + 0x08U)   /* Token index               */
#define KV_REG3_KEY_L   (KV_BASE_ADDR + 0x0CU)   /* Key  [31: 0]              */
#define KV_REG4_KEY_H   (KV_BASE_ADDR + 0x10U)   /* Key  [63:32]              */
#define KV_REG5_VAL_L   (KV_BASE_ADDR + 0x14U)   /* Value[31: 0]              */
#define KV_REG6_VAL_H   (KV_BASE_ADDR + 0x18U)   /* Value[63:32]              */
#define KV_REG7_FEAT    (KV_BASE_ADDR + 0x1CU)   /* Advanced features         */
#define KV_REG8_CFG     (KV_BASE_ADDR + 0x20U)   /* Architecture config       */

/* ---------------------------------------------------------------------------
 * REG0 — Control & Status bit masks
 * --------------------------------------------------------------------------- */
#define KV_START        (1U << 0)   /* W: pulse to launch operation           */
#define KV_IS_WRITE     (1U << 1)   /* W: 1=Write KV, 0=Read KV              */
#define KV_READY        (1U << 2)   /* R: 1=FSM idle, safe to issue command   */
#define KV_HIT          (1U << 3)   /* R: 1=Cache Hit (valid after READ done) */
#define KV_SW_RST       (1U << 4)   /* W: 1=Assert SW reset (clears BRAM)    */

/* ---------------------------------------------------------------------------
 * REG7 — Advanced Features
 * --------------------------------------------------------------------------- */
#define KV_IMMUNE_EN        (1U << 31)  /* Enable Immune Window               */
#define KV_LOCKED_ZONE_EN   (1U << 30)  /* Lock token-0 (Attention Sink)      */
#define KV_WINDOW_SHIFT     16          /* Bits[29:16] = window size          */
#define KV_LOCKED_BOUND_MASK 0x0000FFFFU /* Bits[15:0] = locked sets bound   */

/* ---------------------------------------------------------------------------
 * REG8 — Architecture Config
 * --------------------------------------------------------------------------- */
/* ALGO_SEL [31:30] */
#define KV_ALGO_PLRU    (0U << 30)
#define KV_ALGO_FIFO    (1U << 30)
#define KV_ALGO_RAND    (2U << 30)
#define KV_ALGO_MASK    (3U << 30)

/* SET_SEL [29:28] */
#define KV_SETS_128     (0U << 28)
#define KV_SETS_256     (1U << 28)
#define KV_SETS_512     (2U << 28)
#define KV_SETS_MASK    (3U << 28)

/* WAY_SEL [27] */
#define KV_WAY_FULL     (1U << 27)  /* All 8 ways active                      */
#define KV_WAY_REDUCED  (0U << 27)  /* 4 ways active (power saving)           */

/* RUNTIME_NUM_HEAD [15:0] */
#define KV_NUMHEAD_MASK 0x0000FFFFU

/* ---------------------------------------------------------------------------
 * Timeout guard
 *
 * At 50 MHz: 1 cycle = 20 ns
 *   BRAM hit path  : ~5-10 cycles  → negligible
 *   DDR miss path  : ~50-300 cycles AXI latency + delta codec
 *   Safe upper bound: 50000 cycles = 1 ms — covers worst-case DDR stall
 *
 * NOTE: KV_TIMEOUT_CYCLES applies per KV_WaitReady() call.
 *       KV_Read() calls it twice (before + after), so worst-case
 *       effective timeout per read op = 2 × KV_TIMEOUT_CYCLES.
 * --------------------------------------------------------------------------- */
#define KV_TIMEOUT_CYCLES   50000U

/* =============================================================================
 * Low-level helpers
 * ============================================================================= */

/**
 * KV_WaitReady — poll REG0[2] (READY) until FSM is idle or timeout expires.
 * Returns: 1 if ready, 0 if timed out.
 */
static inline int KV_WaitReady(void) {
    volatile u32 timeout = KV_TIMEOUT_CYCLES;
    while ((Xil_In32(KV_REG0_CTRL) & KV_READY) == 0U) {
        if (--timeout == 0U) return 0;
    }
    return 1;
}

/* =============================================================================
 * Configuration API — call BEFORE any Read/Write operations
 * ============================================================================= */

/**
 * KV_SetAlgoAndSize — select eviction policy and cache geometry.
 *   algo      : KV_ALGO_PLRU | KV_ALGO_FIFO | KV_ALGO_RAND
 *   sets      : KV_SETS_128  | KV_SETS_256  | KV_SETS_512
 *   way_full  : 1 = all 8 ways, 0 = 4 ways
 *   num_heads : number of KV heads (= TRACE_NUM_KV_HEADS = 2)
 * Returns: 1 on success, 0 if HW not ready.
 */
static inline int KV_SetAlgoAndSize(u32 algo, u32 sets,
                                     u8 way_full, u16 num_heads) {
    if (!KV_WaitReady()) return 0;
    u32 cfg = (algo & KV_ALGO_MASK)
            | (sets  & KV_SETS_MASK)
            | (way_full ? KV_WAY_FULL : KV_WAY_REDUCED)
            | (u32)(num_heads & KV_NUMHEAD_MASK);
    Xil_Out32(KV_REG8_CFG, cfg);
    return 1;
}

/**
 * KV_SetFeatures — configure Immune Window and Locked Zone.
 *   immune_en    : 1 = protect recent tokens from eviction
 *   window_size  : number of recent tokens protected (TRACE_WINDOW_SIZE)
 *   locked_en    : 1 = lock token-0 (Attention Sink) permanently
 *   locked_bound : upper set-index of locked zone (48 / N_WAY)
 * Returns: 1 on success, 0 if HW not ready.
 */
static inline int KV_SetFeatures(u8 immune_en, u16 window_size,
                                  u8 locked_en, u16 locked_bound) {
    if (!KV_WaitReady()) return 0;
    u32 feat = (immune_en ? KV_IMMUNE_EN      : 0U)
             | (locked_en ? KV_LOCKED_ZONE_EN : 0U)
             | (((u32)window_size & 0x3FFFU) << KV_WINDOW_SHIFT)
             | ((u32)locked_bound & KV_LOCKED_BOUND_MASK);
    Xil_Out32(KV_REG7_FEAT, feat);
    return 1;
}

/**
 * KV_ResetConfig — clear REG7 and REG8 to default (all features off).
 * Call between benchmark configs to avoid residual state in registers.
 * Note: BRAM valid bits are NOT reset by this — only register state.
 * Use KV_CacheReset() to fully reset BRAM.
 */
static inline void KV_ResetConfig(void) {
    KV_WaitReady();
    Xil_Out32(KV_REG7_FEAT, 0x00000000U);
    Xil_Out32(KV_REG8_CFG,  0x00000000U);
}

/**
 * KV_CacheReset — assert SW reset via REG0[4] to clear BRAM valid bits.
 * Resets the entire cache core including:
 *   - All BRAM valid/dirty bits  (needs >= 512 cycles to clear)
 *   - PLRU/FIFO/RAND eviction state
 *   - FSM back to S_IDLE
 * Does NOT reset AXI wrapper registers (REG1-REG8 preserved).
 * Does NOT reset AXI master/slave FSM (safe for DDR bus).
 *
 * HW requirement: kv_cache_axi_wrapper.sv must implement:
 *   cache_sw_rst_reg <= slv_reg0[4]  (registered, glitch-free)
 *   rst_n_core = rst_n & ~cache_sw_rst_reg
 *   u_kv_core: .rst_n(rst_n_core)
 */
static inline void KV_CacheReset(void) {
    /* Assert SW reset */
    Xil_Out32(KV_REG0_CTRL, KV_SW_RST);
    /* Hold >= 512 cycles for valid_reg[0..511] to clear.
     * usleep(20) = ~1000 cycles @ 50MHz — safe margin. */
    usleep(20);
    /* Deassert SW reset */
    Xil_Out32(KV_REG0_CTRL, 0x00000000U);
    /* Verify FSM is idle before returning */
    KV_WaitReady();
}

/* =============================================================================
 * Data path API
 * ============================================================================= */

/**
 * KV_Write — store a KV pair into the cache.
 * Returns: 1 on success, 0 if HW not ready.
 */
static inline int KV_Write(u16 layer, u16 head, u32 token,
                            u32 kl, u32 kh, u32 vl, u32 vh) {
    if (!KV_WaitReady()) return 0;
    Xil_Out32(KV_REG1_COORD, ((u32)layer << 16) | (u32)head);
    Xil_Out32(KV_REG2_TOKEN, token);
    Xil_Out32(KV_REG3_KEY_L, kl);
    Xil_Out32(KV_REG4_KEY_H, kh);
    Xil_Out32(KV_REG5_VAL_L, vl);
    Xil_Out32(KV_REG6_VAL_H, vh);
    Xil_Out32(KV_REG0_CTRL,  KV_IS_WRITE | KV_START);
    return 1;
}

/**
 * KV_Read — fetch a KV pair from cache (or DDR on miss).
 * Returns:
 *   1  = Cache Hit  (data from BRAM)
 *   0  = Cache Miss (data refilled from DDR)
 *  -1  = HW timeout
 */
static inline int KV_Read(u16 layer, u16 head, u32 token,
                           u32 *kl, u32 *kh, u32 *vl, u32 *vh) {
    if (!KV_WaitReady()) return -1;
    Xil_Out32(KV_REG1_COORD, ((u32)layer << 16) | (u32)head);
    Xil_Out32(KV_REG2_TOKEN, token);
    Xil_Out32(KV_REG0_CTRL,  KV_START);   /* IS_WRITE = 0 */
    if (!KV_WaitReady()) return -1;
    *kl = Xil_In32(KV_REG3_KEY_L);
    *kh = Xil_In32(KV_REG4_KEY_H);
    *vl = Xil_In32(KV_REG5_VAL_L);
    *vh = Xil_In32(KV_REG6_VAL_H);
    return (Xil_In32(KV_REG0_CTRL) & KV_HIT) ? 1 : 0;
}

#endif /* KV_HW_DRIVER_H */